class AIController {
    constructor(aiService, taskModel, activityLog) { this.aiService = aiService; this.taskModel = taskModel; this.activityLog = activityLog; }
    async getRecommendations(req, res, next) { try { const recomendaciones = await this.aiService.generateRecommendations(req.userId); res.json({ total: recomendaciones.length, recomendaciones }); } catch (error) { next(error); } }
    async getPendingRecommendations(req, res, next) { try { const recomendaciones = await this.aiService.getPendingRecommendations(req.userId); res.json({ total: recomendaciones.length, recomendaciones }); } catch (error) { next(error); } }
    async recordFeedback(req, res, next) { try { const { accepted } = req.body; if (typeof accepted !== 'boolean') return res.status(400).json({ error: 'Campo requerido', message: 'El campo "accepted" es requerido (boolean)' }); await this.aiService.recordFeedback(req.params.id, accepted); await this.activityLog.log(req.userId, 'feedback_recomendacion', 'recomendacion', req.params.id, { accepted }); res.json({ message: 'Feedback registrado exitosamente', feedback: { recommendationId: req.params.id, accepted } }); } catch (error) { next(error); } }
    async getRankedTasks(req, res, next) { try { const tareas = await this.aiService.getRankedTasks(req.userId); res.json({ total: tareas.length, tareas: tareas.map((t, i) => ({ ...t, ranking: i + 1 })) }); } catch (error) { next(error); } }
    async optimizeSchedule(req, res, next) { try { const tareas = await this.aiService.getRankedTasks(req.userId); const sugerencias = tareas.slice(0, 5).map((task, index) => ({ rango: `Slot ${index + 1} de hoy`, tarea_id: task.id, tarea_titulo: task.titulo, razon: `Puntuación de IA: ${(task.puntuacion.puntuacion_total * 100).toFixed(1)}%`, tiempo_estimado: task.tiempo_estimado })); res.json({ mensaje: 'Horario optimizado según prioridad IA', sugerencias, recomendacion_general: 'Comienza con las tareas de mayor puntuación para máxima productividad' }); } catch (error) { next(error); } }
    async reprioritizeTasks(req, res, next) { try { const tareas = await this.taskModel.getPending(req.userId); const tareasConPuntuaciones = await Promise.all(tareas.map(async task => ({ ...task, puntuacion: await this.aiService.calculateTaskScore(task) }))); tareasConPuntuaciones.sort((a, b) => b.puntuacion.puntuacion_total - a.puntuacion.puntuacion_total); await this.activityLog.log(req.userId, 'reprioritizar_tareas', 'tarea', null, { cantidad_tareas: tareasConPuntuaciones.length }); res.json({ mensaje: 'Tareas reprioritizadas según IA', tareas: tareasConPuntuaciones.map((t, idx) => ({ id: t.id, titulo: t.titulo, ranking_nuevo: idx + 1, puntuacion_ia: `${(t.puntuacion.puntuacion_total * 100).toFixed(1)}%` })) }); } catch (error) { next(error); } }
    async getFocusPlan(req, res, next) { try { const plan = await this.aiService.generateFocusPlan(req.userId); res.json({ ...plan, timestamp: new Date().toISOString() }); } catch (error) { next(error); } }
    async getInsights(req, res, next) { try { const insights = await this.aiService.getInsights(req.userId); res.json({ insights, timestamp: new Date().toISOString() }); } catch (error) { next(error); } }
    async detectProblems(req, res, next) { try { const problemas = []; const atrasadas = await this.taskModel.getOverdue(req.userId); if (atrasadas.length > 0) problemas.push({ tipo: 'tareas_atrasadas', descripcion: `Tienes ${atrasadas.length} tarea(s) atrasada(s)`, urgencia: 'alta', tareas: atrasadas.slice(0, 3) }); const pendientes = await this.taskModel.getPending(req.userId); if (pendientes.length > 20) problemas.push({ tipo: 'sobrecarga', descripcion: `Tienes ${pendientes.length} tareas pendientes`, urgencia: 'media', recomendacion: 'Considera agrupar tareas similares o delegar algunas' }); const sinFecha = pendientes.filter(t => !t.fecha_vencimiento); if (sinFecha.length > 0) problemas.push({ tipo: 'falta_planificacion', descripcion: `${sinFecha.length} tarea(s) no tienen fecha de vencimiento`, urgencia: 'baja', recomendacion: 'Asigna fechas para mejor seguimiento' }); res.json({ total_problemas: problemas.length, problemas }); } catch (error) { next(error); } }
    async getProductivityMetrics(req, res, next) { try { const { dias = 30 } = req.query; const completadas = await this.taskModel.getCompleted(req.userId, dias); const totalTiempoEstimado = completadas.reduce((sum, t) => sum + (t.tiempo_estimado || 0), 0); const totalTiempoReal = completadas.reduce((sum, t) => sum + (t.tiempo_realizado || 0), 0); const metricas = { periodo_dias: dias, tareas_completadas: completadas.length, tareas_por_dia: (completadas.length / dias).toFixed(2), tiempo_estimado_total: totalTiempoEstimado, tiempo_real_total: totalTiempoReal, eficiencia: totalTiempoEstimado > 0 ? ((totalTiempoReal / totalTiempoEstimado) * 100).toFixed(2) + '%' : 'N/A', promedio_duracion: totalTiempoReal > 0 ? Math.round(totalTiempoReal / completadas.length) : 0 }; res.json({ metricas, recomendacion: metricas.eficiencia > 100 ? 'Tiendes a subestimar el tiempo. Aumenta tus estimaciones.' : metricas.eficiencia < 80 ? 'Eres muy eficiente. Podrías aceptar más tareas.' : 'Tu productividad es consistente' }); } catch (error) { next(error); } }
}

module.exports = AIController;
