class CalendarController {
    constructor(calendarModel, aiService, activityLog) { this.calendarModel = calendarModel; this.aiService = aiService; this.activityLog = activityLog; }
    async getEvents(req, res, next) { try { const { start, end, date } = req.query; let eventos; if (date) eventos = await this.calendarModel.getByDate(req.userId, date); else eventos = await this.calendarModel.getByUserId(req.userId, { start, end }); res.json({ total: eventos.length, eventos }); } catch (error) { next(error); } }
    async createEvent(req, res, next) { try { const { titulo, descripcion, fecha_inicio, fecha_fin, prioridad, recordatorio, color, ubicacion, task_id } = req.body; if (!titulo || !fecha_inicio || !fecha_fin) return res.status(400).json({ error: 'Campos requeridos', message: 'titulo, fecha_inicio y fecha_fin son obligatorios' }); const evento = await this.calendarModel.create(req.userId, { titulo, descripcion, fecha_inicio, fecha_fin, prioridad, recordatorio, color, ubicacion, task_id }); await this.activityLog.log(req.userId, 'crear_evento_calendario', 'evento', evento.id); res.status(201).json({ message: 'Evento creado', evento }); } catch (error) { next(error); } }
    async updateEvent(req, res, next) { try { const eventoExistente = await this.calendarModel.getById(req.params.id); if (!eventoExistente) return res.status(404).json({ error: 'No encontrado' }); if (eventoExistente.user_id !== req.userId) return res.status(403).json({ error: 'Acceso denegado' }); const actualizado = await this.calendarModel.update(req.params.id, req.body); await this.activityLog.log(req.userId, 'actualizar_evento_calendario', 'evento', actualizado.id); res.json({ message: 'Evento actualizado', evento: actualizado }); } catch (error) { next(error); } }
    async deleteEvent(req, res, next) { try { const evento = await this.calendarModel.getById(req.params.id); if (!evento) return res.status(404).json({ error: 'No encontrado' }); if (evento.user_id !== req.userId) return res.status(403).json({ error: 'Acceso denegado' }); await this.calendarModel.delete(req.params.id); await this.activityLog.log(req.userId, 'eliminar_evento_calendario', 'evento', req.params.id); res.json({ message: 'Evento eliminado' }); } catch (error) { next(error); } }
    async suggestFromAI(req, res, next) { try { const tareas = await this.aiService.getRankedTasks(req.userId); const top = tareas.slice(0, 5); const hoy = new Date(); hoy.setHours(9, 0, 0, 0); const creados = []; for (const tarea of top) { const durMin = tarea.tiempo_estimado || 30; const inicio = new Date(hoy); const fin = new Date(inicio.getTime() + durMin * 60 * 1000); const evento = await this.calendarModel.create(req.userId, { task_id: tarea.id, titulo: `Trabajo: ${tarea.titulo}`, descripcion: `Sugerido por IA - puntuación: ${tarea.puntuacion.puntuacion_total}`, fecha_inicio: inicio.toISOString(), fecha_fin: fin.toISOString(), recordatorio: 10 }); creados.push(evento); hoy.setTime(fin.getTime() + (15 * 60 * 1000)); } res.json({ message: 'Eventos sugeridos creados', creados }); } catch (error) { next(error); } }
}

module.exports = CalendarController;
