class TasksController {
    constructor(taskModel, aiService, activityLog) { this.taskModel = taskModel; this.aiService = aiService; this.activityLog = activityLog; }
    async getTasks(req, res, next) { try { const { estado, prioridad, fecha_desde, fecha_hasta, busqueda } = req.query; let tareas; if (busqueda) tareas = await this.taskModel.search(req.userId, busqueda); else { const filtros = { estado, prioridad, fecha_desde, fecha_hasta }; tareas = await this.taskModel.getByUserId(req.userId, filtros); } const tareasConPuntuacion = await Promise.all(tareas.map(async (task) => ({ ...task, ia_score: await this.aiService.calculateTaskScore(task) }))); res.json({ total: tareasConPuntuacion.length, tareas: tareasConPuntuacion }); } catch (error) { next(error); } }
    async getTask(req, res, next) { try { const tarea = await this.taskModel.getById(req.params.id); if (!tarea) return res.status(404).json({ error: 'No encontrado', message: 'La tarea no existe' }); if (tarea.user_id !== req.userId) return res.status(403).json({ error: 'Acceso denegado', message: 'No tienes permiso para ver esta tarea' }); const dependencias = await this.taskModel.getDependencies(tarea.id); const puntuacion = await this.aiService.calculateTaskScore(tarea); res.json({ tarea: { ...tarea, dependencias, ia_score: puntuacion } }); } catch (error) { next(error); } }
    async createTask(req, res, next) { try { const { titulo, descripcion, prioridad, urgencia, fecha_vencimiento, tiempo_estimado, etiquetas } = req.body; if (!titulo) return res.status(400).json({ error: 'Campo requerido', message: 'El título de la tarea es obligatorio' }); const tarea = await this.taskModel.create(req.userId, { titulo, descripcion, prioridad, urgencia, fecha_vencimiento, tiempo_estimado, etiquetas }); await this.activityLog.log(req.userId, 'crear_tarea', 'tarea', tarea.id); const puntuacion = await this.aiService.calculateTaskScore(tarea); res.status(201).json({ message: 'Tarea creada exitosamente', tarea: { ...tarea, ia_score: puntuacion } }); } catch (error) { next(error); } }
    async updateTask(req, res, next) { try { const tareaExistente = await this.taskModel.getById(req.params.id); if (!tareaExistente) return res.status(404).json({ error: 'No encontrado', message: 'La tarea no existe' }); if (tareaExistente.user_id !== req.userId) return res.status(403).json({ error: 'Acceso denegado' }); const tarea = await this.taskModel.update(req.params.id, req.body); await this.activityLog.log(req.userId, 'actualizar_tarea', 'tarea', tarea.id); const puntuacion = await this.aiService.calculateTaskScore(tarea); res.json({ message: 'Tarea actualizada exitosamente', tarea: { ...tarea, ia_score: puntuacion } }); } catch (error) { next(error); } }
    async deleteTask(req, res, next) { try { const tarea = await this.taskModel.getById(req.params.id); if (!tarea) return res.status(404).json({ error: 'No encontrado' }); if (tarea.user_id !== req.userId) return res.status(403).json({ error: 'Acceso denegado' }); await this.taskModel.delete(req.params.id); await this.activityLog.log(req.userId, 'eliminar_tarea', 'tarea', req.params.id); res.json({ message: 'Tarea eliminada exitosamente' }); } catch (error) { next(error); } }
    async getPendingTasks(req, res, next) { try { const tareas = await this.taskModel.getPending(req.userId); const tareasConPuntuacion = await Promise.all(tareas.map(async (task) => ({ ...task, ia_score: await this.aiService.calculateTaskScore(task) }))); tareasConPuntuacion.sort((a, b) => b.ia_score.puntuacion_total - a.ia_score.puntuacion_total); res.json({ total: tareasConPuntuacion.length, tareas: tareasConPuntuacion }); } catch (error) { next(error); } }
    async getOverdueTasks(req, res, next) { try { const tareas = await this.taskModel.getOverdue(req.userId); res.json({ total: tareas.length, tareas }); } catch (error) { next(error); } }
    async getUpcomingTasks(req, res, next) { try { const { dias = 7 } = req.query; const tareas = await this.taskModel.getUpcoming(req.userId, parseInt(dias)); res.json({ total: tareas.length, tareas }); } catch (error) { next(error); } }
    async getTasksByDate(req, res, next) { try { const tareas = await this.taskModel.getByDate(req.userId, req.params.fecha); res.json({ fecha: req.params.fecha, total: tareas.length, tareas }); } catch (error) { next(error); } }
    async completeTask(req, res, next) { try { const { tiempo_realizado } = req.body; const tarea = await this.taskModel.getById(req.params.id); if (!tarea || tarea.user_id !== req.userId) return res.status(404).json({ error: 'Tarea no encontrada' }); const updated = await this.taskModel.update(req.params.id, { estado: 'completada', tiempo_realizado: tiempo_realizado || tarea.tiempo_realizado }); await this.activityLog.log(req.userId, 'completar_tarea', 'tarea', req.params.id); res.json({ message: 'Tarea completada', tarea: updated }); } catch (error) { next(error); } }
    async getStats(req, res, next) { try { const stats = await this.taskModel.countByStatus(req.userId); res.json({ resumen: stats }); } catch (error) { next(error); } }
}

module.exports = TasksController;
